name: Agent Request
description: Request creation of a new AI agent
title: "[AGENT REQUEST] "
labels: ["agent-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Create a New Agent
        Use this template to request a new AI agent. Fill out the fields below or provide details in natural language.

  - type: input
    id: agent_name
    attributes:
      label: Agent Name
      description: Unique identifier for the agent (lowercase, underscores)
      placeholder: "e.g., research_assistant"
    validations:
      required: true

  - type: textarea
    id: role
    attributes:
      label: Role/Purpose
      description: What is this agent's primary function?
      placeholder: "Describe what this agent does and its responsibilities"
    validations:
      required: true

  - type: checkboxes
    id: tool_collections
    attributes:
      label: Tool Collections
      description: Select the tools this agent needs
      options:
        - label: Research (web search, Wikipedia)
        - label: Coding (git, file operations, code analysis)
        - label: File Operations (read, write, search files)
        - label: Twin (codebase understanding, project context)

  - type: dropdown
    id: llm_provider
    attributes:
      label: LLM Provider
      description: Which AI provider should power this agent?
      options:
        - Anthropic Claude
        - OpenAI GPT
        - Google Gemini
      default: 0
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model
      description: Specific model version (leave blank for default)
      placeholder: "e.g., claude-3-5-sonnet-20241022, gpt-4o-mini"

  - type: input
    id: temperature
    attributes:
      label: Temperature
      description: Creativity level (0.0-1.0, default 0.7)
      placeholder: "0.7"

  - type: textarea
    id: system_prompt
    attributes:
      label: System Prompt
      description: Instructions that define the agent's behavior
      placeholder: "You are a specialized agent that..."
      render: text

  - type: checkboxes
    id: memory
    attributes:
      label: Memory
      description: Should this agent remember conversation history?
      options:
        - label: Enable conversation memory
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details about this agent's requirements
      placeholder: "Dependencies, special requirements, integration notes..."
