#!/usr/bin/env python3
"""
Run end-to-end bot tests: send queries → wait → fetch traces → analyze → report.

Usage:
    python scripts/run_bot_tests.py
    python scripts/run_bot_tests.py --wait 30  # Wait 30 seconds before checking traces
"""
import argparse
import subprocess
import time
from datetime import datetime
from pathlib import Path


def run_command(cmd: list, description: str) -> tuple[int, str]:
    """Run a command and return exit code and output."""
    print(f"\n[*] {description}...")
    print(f"    Command: {' '.join(cmd)}")

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60
        )

        print(result.stdout)
        if result.stderr:
            print(f"[STDERR]\n{result.stderr}")

        return result.returncode, result.stdout

    except subprocess.TimeoutExpired:
        print(f"[ERROR] Command timed out after 60s")
        return 1, ""
    except Exception as e:
        print(f"[ERROR] Command failed: {e}")
        return 1, ""


def main():
    parser = argparse.ArgumentParser(
        description="Run end-to-end bot tests"
    )

    parser.add_argument(
        "--wait",
        type=int,
        default=15,
        help="Seconds to wait after sending queries (default: 15)"
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=10,
        help="Number of traces to fetch (default: 10)"
    )

    args = parser.parse_args()

    test_start = datetime.now()

    print("=" * 80)
    print(f"[E2E TEST] RIVET CEO Bot - {test_start.strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 80)

    # STEP 1: Send test queries
    exit_code, output = run_command(
        ["poetry", "run", "python", "scripts/test_bot.py"],
        "Sending test queries to bot"
    )

    if exit_code != 0:
        print("[ERROR] Failed to send test queries")
        return 1

    # STEP 2: Wait for processing
    print(f"\n[*] Waiting {args.wait} seconds for bot to process queries...")
    for i in range(args.wait, 0, -1):
        print(f"    {i}s remaining...", end='\r')
        time.sleep(1)
    print()

    # STEP 3: Fetch traces
    exit_code, output = run_command(
        ["poetry", "run", "python", "scripts/pull_langsmith_runs.py",
         "--project", "rivet-ceo-bot", "--limit", str(args.limit)],
        "Fetching LangSmith traces"
    )

    if exit_code != 0:
        print("[ERROR] Failed to fetch traces")
        return 1

    # STEP 4: Analyze traces
    exit_code, output = run_command(
        ["poetry", "run", "python", "scripts/check_traces.py",
         "--limit", str(args.limit)],
        "Analyzing traces"
    )

    if exit_code != 0:
        print("[ERROR] Failed to analyze traces")
        return 1

    # STEP 5: Save results to docs
    test_end = datetime.now()
    duration = (test_end - test_start).total_seconds()

    results_path = Path("docs/TEST_RESULTS.md")

    print(f"\n[*] Saving results to {results_path}...")

    with open(results_path, 'w', encoding='utf-8') as f:
        f.write(f"# RIVET CEO Bot Test Results\n\n")
        f.write(f"**Test Run:** {test_start.strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"**Duration:** {duration:.2f}s\n\n")
        f.write(f"---\n\n")
        f.write(f"## Test Configuration\n\n")
        f.write(f"- Wait time: {args.wait}s\n")
        f.write(f"- Traces fetched: {args.limit}\n\n")
        f.write(f"---\n\n")
        f.write(f"## Trace Files\n\n")
        f.write(f"Check `evals/langsmith/runs/*.md` for detailed traces.\n\n")
        f.write(f"---\n\n")
        f.write(f"## Analysis Output\n\n")
        f.write(f"```\n{output}\n```\n\n")
        f.write(f"---\n\n")
        f.write(f"*Generated by run_bot_tests.py*\n")

    print(f"[OK] Results saved to {results_path}")

    # Final summary
    print()
    print("=" * 80)
    print("[TEST COMPLETE]")
    print(f"  Duration: {duration:.2f}s")
    print(f"  Results: {results_path}")
    print(f"  Traces: evals/langsmith/runs/*.md")
    print("=" * 80)

    return 0


if __name__ == "__main__":
    exit(main())
